import { Profile, Experience, Skill, Formation, Activity, Project } from '../types'

export const mockProfile: Profile = {
  name: 'Alexandre Plana',
  handle: 'alexandre-plana',
  title: 'Développeur Front End Web',
  subtitle: 'Industrie · UI/UX · Multi Plateforme',
  bio: 'Développeur Front End spécialisé industrie depuis 13 ans. D\'abord sur des interfaces 3D / VR pour EDF, RTE, AREVA et DCNS, puis sur une application AR mobile multi-plateforme, aujourd\'hui sur des architectures web micro-frontend pour l\'IIoT. La techno évolue, le domaine reste : des interfaces complexes pour des environnements industriels exigeants. Sensibilité UI/UX forgée par la pratique du design sur l\'ensemble du parcours.',
  company: 'Consultant R&D · Datacorp / Schneider Electric',
  location: 'France',
  email: 'alexandre.plana@gmail',
  phone: '06.71.03.97.84',
  followers: 142,
  following: 38,
  contributions: 1842,
  seeking: 'Poste Front End web dans un contexte industriel · Vue.js ou React · TypeScript · micro-frontend · équipe orientée qualité & UX',
  langs: [
    { label: 'Français', level: 'Natif' },
    { label: 'Anglais', level: 'Technique' },
  ],
  languages: [
    { name: 'TypeScript', pct: 35, color: '#3178c6' },
    { name: 'C#', pct: 35, color: '#178600' },
    { name: 'HTML5/CSS', pct: 20, color: '#e34c26' },
    { name: 'Dart', pct: 10, color: '#00b4d8' },
  ],
  awards: [
    { year: '2012', title: 'Laval Virtual', desc: 'Prix du jury — reconstitution virtuelle Abbaye d\'Evron' },
    { year: '2011', title: 'Laval Virtual', desc: '1ère place — Hackaton réalité augmentée' },
  ],
  interests: ['🎮 Jeux', '🚵 VTT', '🥾 Rando', '🍳 Cuisine'],
  uiuxHighlight: {
    label: '🎨 Culture UI/UX',
    desc: 'Pratique du design sur l\'ensemble du parcours — de la maquette Figma au composant en production.',
    tools: ['Figma', 'Adobe XD', 'Design System', 'Prototypage'],
  },
}

export const mockExperiences: Experience[] = [
  {
    id: 1,
    company: 'Schneider Electric',
    employer: 'Consultant R&D — Datacorp',
    period: '2017 – 2026',
    type: 'consulting',
    missions: [
      {
        id: 11,
        featured: true,
        name: 'schneider/iiot-edge-ieca',
        badge: 'Lead FE Développeur',
        period: '2023 – 2026',
        context: 'Industrial Automation IIoT 2.0 Edge (IECA)',
        desc: 'Développement d\'Edge compute apps industrielles sur la plateforme Goodenough (single-spa). Architecture micro-frontend IIoT 2.0, intégration de composants Vue 3 + TypeScript en équipe. Conception UI des tableaux de bord industriels en lien avec les équipes UX.',
        metrics: [],
        stack: 'Vue 3.4 · TypeScript 5.x · single-spa 6 · Jest · HTML5 · CSS3 · Git · JSS · Figma · Jira',
        tags: ['vue3', 'ts', 'single-spa', 'jest', 'html', 'css', 'git', 'figma', 'jira'],
        lang: 'Vue.js',
        langColor: '#41b883',
        stars: '1.2k',
      },
      {
        id: 12,
        featured: false,
        name: 'schneider/aoa-ar-app',
        badge: 'Développeur C# / Unity',
        period: '2017 – 2023',
        context: 'Augmented Operator Advisor (AOA) — Application AR industrielle',
        desc: 'Développement pendant 6 ans d\'une application AR multi-plateforme (Android, iOS, Windows) pour opérateurs industriels Schneider Electric. Conception et implémentation des interfaces opérateur, gestion des états complexes de la couche AR.',
        metrics: [
          { value: '6 ans', label: 'développement\ncontinu' },
          { value: '3', label: 'plateformes\nsimultanées' },
          { value: 'AR', label: 'temps réel\nterrain' },
        ],
        stack: 'Unity 3D · C# · ARKit · ARCore · Figma · UI/UX · Scrum · Jira',
        tags: ['unity', 'c#', 'ar', 'mobile', 'uiux', 'figma', 'agile', 'jira'],
        lang: 'C#',
        langColor: '#178600',
        stars: '980',
      },
    ],
  },
  {
    id: 2,
    company: 'Oreka Ingénierie',
    employer: 'Développeur C# / Unity 3D',
    period: '2013 – 2017',
    type: 'employee',
    missions: [
      {
        id: 21,
        featured: false,
        name: 'oreka/xr-projects',
        badge: 'Développeur C# / Unity 3D',
        period: '2013 – 2017',
        context: 'Projets VR/AR industriels — EDF · RTE · AREVA · DCNS · Énergies renouvelables',
        desc: 'Développement d\'interfaces 3D et de simulations VR/AR pour grands comptes de l\'industrie lourde et de l\'énergie. Projets livrés : EDF Aeroball, AREVA EMEM, DCNS simulateurs, RTE supervision, SUEZ radio protection.',
        metrics: [
          { value: '6+', label: 'projets\nindustriels' },
          { value: '5', label: 'clients grands\ncomptes' },
          { value: 'VR/AR', label: 'temps réel\nUnity 3D' },
        ],
        stack: 'Unity 3D · C# · WPF · WinForm · SolidWorks · 3ds Max · Figma',
        tags: ['unity', 'c#', 'wpf', 'winform', 'solidworks', '3dsmax', 'vr', 'uiux', 'figma', 'desktop'],
        lang: 'C#',
        langColor: '#178600',
        stars: '543',
      },
    ],
  },
]

export const mockSkills: Skill[] = [
  {
    cat: '⭐ Développement Web',
    featured: true,
    tags: [
      { l: 'Vue.js', k: 'vue' },
      { l: 'TypeScript', k: 'ts' },
      { l: 'JavaScript', k: 'js' },
      { l: 'HTML5', k: 'html' },
      { l: 'CSS3', k: 'css' },
      { l: 'Jest', k: 'jest' },
      { l: 'single-spa', k: 'spa' },
      { l: 'Git', k: 'git' },
    ],
  },
  {
    cat: '// UI/UX Design',
    featured: false,
    tags: [
      { l: 'Figma', k: 'figma' },
      { l: 'Adobe XD', k: 'figma' },
      { l: 'User Research', k: 'uiux' },
      { l: 'Wireframing', k: 'uiux' },
      { l: 'Prototypage', k: 'uiux' },
      { l: 'Design System', k: 'uiux' },
      { l: 'UX industriel', k: 'uiux' },
      { l: 'UI opérateur', k: 'uiux' },
    ],
  },
  {
    cat: '// Développement Mobile',
    featured: false,
    tags: [
      { l: 'Flutter', k: 'flutter' },
      { l: 'Dart', k: 'dart' },
      { l: 'iOS', k: 'mobile' },
      { l: 'Android', k: 'mobile' },
    ],
  },
  {
    cat: '// 3D Temps Réel & XR',
    featured: false,
    tags: [
      { l: 'Unity 3D', k: 'unity' },
      { l: 'C#', k: 'c#' },
      { l: 'Réalité Augmentée', k: 'ar' },
      { l: 'Réalité Virtuelle', k: 'vr' },
      { l: '3ds Max', k: '3d' },
      { l: '3D Temps Réel', k: '3d-temps-réel' },
    ],
  },
  {
    cat: '// Outils & Méthodologie',
    featured: false,
    tags: [
      { l: 'Git', k: 'git' },
      { l: 'Jira', k: 'jira' },
      { l: 'Scrum', k: 'agile' },
      { l: 'Agile', k: 'agile' },
    ],
  },
  {
    cat: '// Soft Skills',
    featured: false,
    tags: [
      { l: 'Créativité', k: 'green' },
      { l: 'Travail d\'équipe', k: 'green' },
      { l: 'Adaptabilité', k: 'green' },
      { l: 'Curiosité', k: 'green' },
    ],
  },
]

export const mockFormation: Formation[] = [
  {
    label: '📌 Licence',
    title: 'Licence 3D Temps Réel',
    sub: '3DI Laval · 2012–2013',
    meta: '3D temps réel · Réalité virtuelle · Unity 3D',
    bg: '#dcfce7',
    color: '#166534',
  },
  {
    label: '📌 BTS',
    title: 'BTS Communication Visuelle opt. Multimédia',
    sub: '3DI Laval · 2010–2012',
    meta: 'Print · Multimédia · Web · Vidéo',
    bg: '#dcfce7',
    color: '#166534',
  },
  {
    label: '📌 Formations',
    title: 'C# · Dart · TypeScript · Flutter · UI-UX',
    sub: 'Datacorp · 2017',
    meta: 'Formations professionnelles certifiées',
    bg: '#dbeafe',
    color: '#1e40af',
  },
  {
    label: '📌 Stage',
    title: 'Stage Polymorph (3S)',
    sub: 'YOM Graphic Design · Prisma (53)',
    meta: 'Design graphique · Communication visuelle',
    bg: '#dcfce7',
    color: '#166534',
  },
]

export const mockActivity: Activity[] = [
  {
    id: 1,
    icon: '🔀',
    type: 'blue',
    action: 'Merged a PR in',
    repo: 'schneider/iiot-edge-ieca',
    detail: 'feat: new Edge dashboard widget',
    time: '3 days ago',
  },
  {
    id: 2,
    icon: '⭐',
    type: 'green',
    action: 'Starred',
    repo: 'vuejs/core and vitejs/vite',
    detail: '',
    time: '1 week ago',
  },
  {
    id: 3,
    icon: '💬',
    type: 'orange',
    action: 'Commented on issue #88 in',
    repo: 'schneider/iiot-edge-ieca',
    detail: 'single-spa routing fix',
    time: '2 weeks ago',
  },
  {
    id: 4,
    icon: '🎉',
    type: 'green',
    action: 'Released v3.1.0 in',
    repo: 'schneider/aoa-ar-app',
    detail: 'Multi-platform AR build',
    time: '1 month ago',
  },
]

export const mockProjects: Project[] = [
  {
    id: 1,
    name: 'schneider/iiot-edge-ieca',
    company: 'Schneider Electric',
    role: 'Frontend Developer',
    period: '2023 – 2026',
    context: 'Industrial Automation IIoT 2.0 Edge (IECA)',
    desc: 'Plateforme Cloud IIoT pour l\'automatisation industrielle. Tablespaces de contrôle d\'usines, monitoring en temps réel des machines, architecture micro-frontend.',
    stack: 'Vue 3.4 · TypeScript 5.x · single-spa 6 · Jest · HTML5 · CSS3 · Figma · Jira',
    tags: ['vue3', 'ts', 'single-spa', 'jest', 'html', 'css', 'git', 'figma'],
    link: 'https://github.com/schneider-electric/iiot-edge',
    highlights: ['Multi-site deployment', 'Real-time monitoring', 'Micro-frontend architecture'],
  },
  {
    id: 2,
    name: 'schneider/aoa-ar-app',
    company: 'Schneider Electric',
    role: 'C# / Unity Developer',
    period: '2017 – 2023',
    context: 'Augmented Operator Advisor (AOA) — Industrial AR Application',
    desc: 'Application AR multiplateforme pour opérateurs industriels Schneider Electric. Interfaces opérateur en AR, overlay des données machines en temps réel, gestion complexe de la couche AR.',
    stack: 'Unity 3D · C# · ARKit · ARCore · Figma · iOS · Android · Windows',
    tags: ['unity', 'c#', 'ar', 'mobile', 'uiux', 'figma', 'agile'],
    link: 'https://github.com/schneider-electric/aoa',
    highlights: ['Cross-platform deployment', '6 years continuous development', '3 simultaneous platforms'],
  },
  {
    id: 3,
    name: 'simulhom',
    company: 'Oreka Ingénierie',
    role: 'C# / Unity Developer',
    period: '2015 – 2017',
    context: 'Outil de prévention des TMS (Troubles Musculo-Squelettiques)',
    desc: 'Simulateur ergonomique 3D pour la prévention des TMS en milieu industriel. Analyse posturale temps réel, feedback visuel des risques, interface opérateur intuitive.',
    stack: 'Unity 3D · C# · 3ds Max · Ergonomie · Biomécanique',
    tags: ['unity', 'c#', '3d-temps-réel', 'vr', 'ergonomics'],
    highlights: ['Ergonomic analysis', 'Real-time biomechanical feedback', 'Industrial deployment'],
  },
  {
    id: 4,
    name: 'oreka/dosicase',
    company: 'Oreka Ingénierie',
    role: 'Conception & Design UI/UX',
    period: '2015 – 2017',
    context: 'Dosicase — Simulateur de radioactivité pour chantiers école',
    desc: 'Outil de simulation de radioactivité destiné aux chantiers école pour la formation en radioprotection. Conception de l\'interface utilisateur et design UX pour rendre accessible la compréhension des risques radiologiques. Focus sur la pédagogie et l\'apprentissage pratique.',
    stack: 'UX/UI Design · Simulation · Radioprotection · Web Interface',
    tags: ['uiux', 'design', 'web', 'radioprotection', 'dosimetry', 'figma'],
    link: 'https://www.dosicase.com/#NS',
    highlights: ['Design interface utilisateur', 'Optimisation ergonomique', 'Conformité radioprotection'],
  },
  {
    id: 5,
    name: 'areva/emem',
    company: 'AREVA / Oreka Ingénierie',
    role: 'C# / 3D Developer',
    period: '2014 – 2016',
    context: 'EMEM (Enceinte Mobile d\'Évacuation de Matériel) — Nuclear Safety',
    desc: 'Simulation 3D interactive d\'une enceinte mobile nucléaire. Visualisation 3D des flux, gestion des matériaux radioactifs, interfaces de contrôle temps réel pour opérateurs.',
    stack: 'Unity 3D · C# · SolidWorks · Nuclear simulation · WPF',
    tags: ['unity', 'c#', '3d-temps-réel', 'nuclear', 'desktop'],
    highlights: ['Nuclear safety compliance', '3D CAD integration', 'Operator training'],
  },
  {
    id: 6,
    name: 'edf/aeroball',
    company: 'EDF / Oreka Ingénierie',
    role: 'C# / 3D Developer',
    period: '2014 – 2015',
    context: 'Aeroball — Serious Game pour poste de contrôle nucléaire',
    desc: 'Serious game de formation pour l\'utilisation du poste de contrôle Aeroball en milieu nucléaire. Simulation 3D interactive, développement C# et modélisation 3D pour reproduire fidèlement les procédures opérationnelles.',
    stack: 'Unity 3D · C# · Modélisation 3D · Nuclear Training · Simulation',
    tags: ['unity', 'c#', '3d-temps-réel', 'nuclear', 'training', 'desktop'],
    highlights: ['Nuclear control station simulation', '3D modeling', 'Operator training'],
  },
  {
    id: 7,
    name: 'suez/serious-game-radioprotection',
    company: 'SUEZ / Oreka Ingénierie',
    role: 'C# / 3D Developer',
    period: '2014 – 2015',
    context: 'Formation en Radioprotection — Nuclear Safety Training',
    desc: 'Module de formation interactive 3D sur la radioprotection et les procédures de sécurité nucléaire. Simulations de scénarios d\'accident, gestion des équipes de secours.',
    stack: 'Unity 3D · C# · 3D Modeling · Educational Design',
    tags: ['unity', 'c#', '3d-temps-réel', 'training', 'education'],
    highlights: ['Interactive learning', 'Scenario simulation', 'Safety compliance training'],
  },
  {
    id: 8,
    name: 'suez/maintenance-generateurs-de-vapeurs',
    company: 'SUEZ / Oreka Ingénierie',
    role: 'C# / 3D Developer',
    period: '2014 – 2015',
    context: 'Maintenance Générateurs de Vapeurs — Serious Game pour arrêts de tranche',
    desc: 'Serious game destiné à préparer les interventions durant les arrêts de tranche pour la maintenance des générateurs de vapeurs. Simulation 3D temps réel, développement C# pour reproduire les procédures complexes de maintenance en environnement nucléaire.',
    stack: 'Unity 3D · C# · 3D Temps Réel · Nuclear Maintenance · Simulation',
    tags: ['unity', 'c#', '3d-temps-réel', 'nuclear', 'training', 'desktop'],
    highlights: ['Steam generator maintenance simulation', 'Outage preparation', 'Real-time 3D training'],
  },
  {
    id: 9,
    name: 'chu-caen/emsim-basic',
    company: 'CHU de Caen / Oreka Ingénierie',
    role: 'C# / 3D Developer',
    period: '2013 – 2015',
    context: 'Radioprotection pour la Chirurgie Interventionnelle',
    desc: 'Simulation 3D pour la formation des équipes chirurgicales. Dosimétrie en temps réel, visualisation des zones sensibles aux radiations, protocole de radioprotection opérateur.',
    stack: 'Unity 3D · C# · Medical 3D · Dosimetry · Healthcare',
    tags: ['unity', 'c#', '3d-temps-réel', 'medical', 'healthcare'],
    highlights: ['Medical accuracy', 'Real-time dosimetry', 'Surgical training'],
  },
]
