import { Profile, Experience, Skill, Formation, Activity, Project, PersonalProject } from '../types'

export const mockProfile: Profile = {
  name: 'Alexandre Plana',
  handle: 'alexandre-plana',
  title: 'Développeur Front End',
  subtitle: 'Industrie · UI/UX · Multi Plateforme',
  bio: 'Développeur Front End spécialisé industrie depuis 13 ans. D\'abord sur des interfaces 3D / VR pour EDF, RTE, AREVA et DCNS, puis sur une application AR mobile multi-plateforme, aujourd\'hui sur des architectures web micro-frontend pour l\'IIoT. La techno évolue, le domaine reste : des interfaces complexes pour des environnements industriels exigeants. Sensibilité UI/UX forgée par la pratique du design sur l\'ensemble du parcours.',
  company: 'Consultant R&D · Datacorp / X-PERT',
  location: 'France',
  email: 'alexandre.plana@gmail',
  phone: '06.71.03.97.84',
  langs: [
    { label: 'Français', level: 'Natif' },
    { label: 'Anglais', level: 'Technique' },
  ],
  languages: [
    { name: 'TypeScript', pct: 35, color: '#3178c6' },
    { name: 'C#', pct: 35, color: '#178600' },
    { name: 'HTML5/CSS', pct: 20, color: '#e34c26' },
    { name: 'Dart', pct: 10, color: '#00b4d8' },
  ],
  interests: ['🎮 Jeux', '🚵 VTT', '🥾 Rando', '🍳 Cuisine'],
}

export const mockExperiences: Experience[] = [
  {
    id: 3,
    company: 'Datacorp',
    employer: 'Consultant R&D — X-PERT',
    period: '2026',
    missions: [
      {
        id: 31,
        featured: true,
        name: 'x-pert/xistar',
        badge: 'Développeur full stack',
        period: '2026',
        context: 'Xistar — Marine Command Center',
        desc: "Développement de Xistar, poste de commandement tactique maritime dans le navigateur : un produit unique couvrant la boucle capteur → opérateur → décision → action → analyse. Image tactique temps réel (MapLibre + deck.gl, symbologie OTAN APP-6D, grille MGRS, bathymétrie), conduite de missions et de drones avec enchaînements automatiques et humain dans la boucle, mur d'écrans synchronisé avec push distant, rejeu complet des opérations. Architecture « pont » : adaptateurs isolés aux frontières (AIS, NMEA, CoT, MAVLink) vers un modèle canonique diffusé via MQTT et Socket.io. Une seule base de code produit trois déclinaisons (défense, portuaire, démo) grâce à un registre de features par profil avec lazy loading et tree-shaking.",
        cardSummary: "Développeur full stack sur Xistar, poste de commandement tactique maritime dans le navigateur : image tactique temps réel #maplibre #deckgl en symbologie OTAN APP-6D, conduite de missions et de drones, mur d'écrans synchronisé et rejeu complet des opérations. Temps réel bout-en-bout #mqtt #socketio, une base de code → trois produits (défense, portuaire, démo) via un registre de features #treeshaking, qualité outillée #vitest #gitlabci.",
        tasks: [
          "Développer l'interface opérateur : situation tactique, panneaux de missions, console d'alertes BAM/CAM avec escalade et humain dans la boucle",
          'Implémenter le rendu cartographique MapLibre + deck.gl : symbologie APP-6D, trails, vecteurs de route, grille MGRS, bathymétrie',
          'Concevoir le système de features à registre par profil : manifests, lazy loading, builds tree-shakés — trois produits sans fork fonctionnel',
          "Brancher le temps réel bout-en-bout : flux capteurs (AIS, NMEA, CoT, MAVLink) adaptés en frontière puis diffusés via MQTT et Socket.io jusqu'à l'UI",
          "Mettre en place le rejeu synchronisé multi-écrans et le mur d'écrans avec push distant de vues",
          'Outiller la qualité : Vitest front et back, lint, pipeline GitLab CI en 5 étapes avec déploiement taggé et smoke tests',
        ],
        priorityActionIndexes: [0, 3],
        isCurrent: true,
        tags: ['maplibre', 'deck.gl', 'mqtt', 'socket.io', 'openbridge', 'vitest', 'gitlab ci'],
        type: 'mission',
      },
      {
        id: 32,
        featured: false,
        name: 'x-pert/xistar-fleet-sim',
        badge: 'Développeur full stack',
        period: '2026',
        context: 'Simulateur de drones & flotte navale',
        desc: "Simulateur Node.js de drones et de flotte navale alimentant Xistar en flux réalistes (positions, états, détections) pour les démos et le développement — conforme au principe « zéro donnée mock » de la plateforme.",
        tags: ['node', 'ts', 'mqtt', 'simulation'],
        type: 'projet',
      },
      {
        id: 33,
        featured: false,
        name: 'x-pert/xistar-mobile',
        badge: 'Développeur full stack',
        period: '2026',
        context: 'App mobile — alertes & ordres',
        desc: "Application mobile de réception des alertes BAM/CAM et d'émission d'ordres (escalade, ordre de retour) : l'opérateur reste dans la boucle depuis le terrain.",
        tags: ['react', 'mobile', 'socket.io', 'ts'],
        type: 'projet',
      },
      {
        id: 34,
        featured: false,
        name: 'x-pert/xistar-wall-emulator',
        badge: 'Développeur full stack',
        period: '2026',
        context: "Émulateur de mur d'écrans",
        desc: "Émulateur de mur d'écrans pour développer et démontrer la conduite multi-vues sans salle physique : ensembles d'écrans, mission board, push distant de vues. Stack React / Vite.",
        tags: ['react', 'vite', 'ts', 'desktop'],
        type: 'projet',
      },
    ],
  },
  {
    id: 1,
    company: 'Datacorp',
    employer: 'Consultant R&D — Schneider Electric',
    period: '2017 – 2026',
    missions: [
      {
        id: 11,
        featured: true,
        name: 'schneider-electric/iiot-edge-ieca',
        badge: 'Front end developer',
        period: '2023 – 2026',
        context: 'Industrial Automation Edge (IECA)',
        desc: "Développement d'applications Edge industrielles en architecture micro-frontend (single-spa) avec Vue 3 + TypeScript au sein d'une équipe Scrum pluridisciplinaire. Contribution significative au MFE utilitaire partagé : conception d'une table générique configurable, base de routing commune, sélecteur de propriétés et composants transverses réutilisés par l'ensemble des équipes du projet. Développement d'un prototype d'application mobile d'alertes pour opérateurs en astreinte, présenté aux PO et envisagé pour une potentielle implémentation client.",
        tasks: [
          'Concevoir et développer des composants front réutilisables par les différentes équipes du projet, dont une table générique configurable, une base de routing commune et un sélecteur de propriétés',
          'Implémenter les tests unitaires avec Jest — tests composants, stores Pinia et fonctions utilitaires',
          "Surveiller les performances et le bon fonctionnement de l'application, et améliorer la qualité du code via SonarQube",
          "Amélioration continue de l'architecture et de la scalabilité du projet",
          "Participer aux code reviews et contribuer à la montée en compétence de l'équipe sur les bonnes pratiques front",
        ],
        priorityActionIndexes: [0, 1],
        retrospective: "Cette mission m'a permis de structurer des pratiques frontend robustes dans un environnement industriel exigeant, et de confirmer ma capacité à monter en compétence rapidement sur une nouvelle stack.",
        tags: ['vue3', 'ts', 'single-spa', 'docker', 'jest', 'html', 'css', 'git', 'figma', 'jira'],
        type: 'mission',
      },
      {
        id: 12,
        featured: false,
        name: 'schneider-electric/aoa-ar-app',
        badge: 'Développeur C# / Unity',
        period: '2017 – 2023',
        context: 'Augmented Operator Advisor (AOA) — Application AR industrielle',
        desc: "Six ans sur un projet structurant, dans un environnement de qualité industrielle. Cette mission m'a forgé une rigueur sur les tests, l'architecture et la maintenabilité que j'applique depuis sur chaque projet.",
        tasks: [
          'Conception et développement d\'une interface entièrement responsive (iOS, Android, Windows - modes portrait et paysage)',
          'Compilation, préparation et déploiement des applications sur les différents stores (Google Play, App Store, SESU)',
          'Création d\'un outil dédié aux tests unitaires sous Unity 3D, intégré aux phases de pre-build et post-build',
          'Mise en place d\'un système de styles externalisé permettant de livrer des versions personnalisées aux couleurs des clients (notamment pour les OEM)',
          "Conception de l'architecture front-end de l'application : découpage modulaire, conventions de code et séparation des responsabilités",
          "Développement d'un système offline avec synchronisation automatique des données dès le rétablissement de la connexion",
          "Désérialisation et gestion de la rétrocompatibilité entre les versions de projets : lecture des anciens formats, migration silencieuse à la volée",
          "Implémentation de la couche de communication avec le serveur de projets : requêtes HTTP, gestion des erreurs réseau et logique de reconnexion",
          "Gestion du cycle de vie des données applicatives : invalidation du cache local, stratégie de rafraîchissement et purge des données obsolètes",
        ],
        priorityActionIndexes: [4, 7],
        retrospective: 'Ce projet m\'a énormément apporté, autant sur le plan technique que personnel. Il m\'a permis de travailler sur un environnement véritablement structuré, avec des processus propres aux grandes entreprises, des standards de qualité bien plus élevés que ceux de mes expériences précédentes, et une vraie prise de conscience de l\'importance des tests unitaires et de l\'architecture pour assurer la maintenabilité d\'un projet dans la durée.',
        tags: ['unity', 'c#', 'ar', 'mobile', 'uiux', 'figma', 'agile', 'jira'],
        type: 'mission',
      },
    ],
  },
  {
    id: 2,
    company: 'Oreka Ingénierie',
    employer: 'Développeur C# / Unity 3D',
    period: '2013 – 2017',
    missions: [
        {
          id: 21,
          featured: false,
          name: 'oreka/xr-projects',
          badge: 'Développeur C# / Unity 3D',
          period: '2013 – 2017',
          context: 'Projets VR/AR industriels — EDF · RTE · AREVA · DCNS · Énergies renouvelables',
          desc: "Développeur C# / Unity 3D sur des projets VR/AR à forte dimension industrielle pour de grands comptes (EDF, Suez, DCNS, RTE, MBDA) dans des contextes sensibles (nucléaire, armement). Analyse des besoins clients, participation aux propositions commerciales, modélisation et intégration 3D, conception UI/UX pour environnements immersifs, développement d'applications interactives haute performance, optimisation des performances et livraison de versions clients.",
          tasks: [
            'Développement d\'interfaces et de systèmes interactifs 2D/3D sous Unity (C#) : architecture des scènes, scripting, gestion des événements, systèmes d\'interaction VR/AR',
            'Intégration et traitement de modèles issus de la CAO (SolidWorks) : optimisation mesh, baking, LOD, lightmaps, réglages matériaux/shaders',
            'Optimisation des performances en environnements industriels : profiling Unity, réduction du coût CPU/GPU, pooling d\'objets, optimisation des assets',
            'Développement de modules techniques spécifiques : gestion d\'I/O, logique métier, systèmes d\'état, chargement dynamique de contenu',
            'Implémentation de scénarios interactifs basés sur les procédures métier : graphes d\'états, logiques conditionnelles, triggers',
            'Conception d\'interfaces immersives adaptées aux usages VR/AR : ergonomie, spatialisation, interactions contrôleur/manette',
            'Participation à la définition technique des besoins client : spécifications, faisabilité, choix technologiques, maquettes fonctionnelles',
            'Préparation et livraison de versions internes et clients : automatisation partielle des builds, debug, support des démonstrations',
          ],
          priorityActionIndexes: [2, 6],
          retrospective: "Quatre ans de projets industriels variés qui m'ont appris à comprendre les besoins métier avant d'écrire la première ligne de code, à travailler avec des exigences techniques élevées, et à collaborer efficacement dans des environnements pluridisciplinaires.",
          tags: ['unity', 'c#', 'wpf', 'winform', 'solidworks', '3dsmax', 'vr', 'uiux', 'figma', 'desktop'],
          type: 'mission',
        },
        {
          id: 22,
          featured: false,
          name: 'simulhom',
          badge: 'C# / Unity Developer',
          period: '2015 – 2017',
          context: 'Outil de prévention des TMS (Troubles Musculo-Squelettiques)',
          desc: 'Simulateur ergonomique 3D pour la prévention des TMS en milieu industriel. Analyse posturale temps réel, feedback visuel des risques, interface opérateur intuitive.',
          tasks: ['Développement Unity 3D', 'Analyse posturale temps réel', 'Interface opérateur intuitive'],
          tags: ['unity', 'c#', '3d-temps-réel', 'vr', 'ergonomics'],
          type: 'projet',
        },
        {
          id: 23,
          featured: false,
          name: 'oreka/dosicase',
          badge: 'Conception & Design UI/UX',
          period: '2015 – 2017',
          context: 'Dosicase — Simulateur de radioactivité pour chantiers école',
          desc: 'Outil de simulation de radioactivité destiné aux chantiers école pour la formation en radioprotection. Conception de l\'interface utilisateur et design UX pour rendre accessible la compréhension des risques radiologiques. Focus sur la pédagogie et l\'apprentissage pratique.',
          tasks: ['Conception UI/UX', 'Simulation radioprotection', 'Design pédagogique'],
          tags: ['uiux', 'design', 'web', 'radioprotection', 'dosimetry', 'figma'],
          type: 'projet',
        },
        {
          id: 24,
          featured: false,
          name: 'areva/emem',
          badge: 'C# / 3D Developer',
          period: '2014 – 2016',
          context: 'EMEM (Enceinte Mobile d\'Évacuation de Matériel) — Nuclear Safety',
          desc: 'Simulation 3D interactive d\'une enceinte mobile nucléaire. Visualisation 3D des flux, gestion des matériaux radioactifs, interfaces de contrôle temps réel pour opérateurs.',
          tasks: ['Simulation 3D', 'Gestion matériaux radioactifs', 'Interfaces temps réel'],
          tags: ['unity', 'c#', '3d-temps-réel', 'nuclear', 'desktop'],
          type: 'projet',
        },
        {
          id: 25,
          featured: false,
          name: 'edf/aeroball',
          badge: 'C# / 3D Developer',
          period: '2014 – 2015',
          context: 'Aeroball — Serious Game pour poste de contrôle nucléaire',
          desc: 'Serious game de formation pour l\'utilisation du poste de contrôle Aeroball en milieu nucléaire. Simulation 3D interactive, développement C# et modélisation 3D pour reproduire fidèlement les procédures opérationnelles.',
          tasks: ['Serious game', 'Simulation 3D', 'Modélisation procédurale'],
          tags: ['unity', 'c#', '3d-temps-réel', 'nuclear', 'training', 'desktop'],
          type: 'projet',
        },
        {
          id: 26,
          featured: false,
          name: 'suez/serious-game-radioprotection',
          badge: 'C# / 3D Developer',
          period: '2014 – 2015',
          context: 'Formation en Radioprotection — Nuclear Safety Training',
          desc: 'Module de formation interactive 3D sur la radioprotection et les procédures de sécurité nucléaire. Simulations de scénarios d\'accident, gestion des équipes de secours.',
          tasks: ['Formation radioprotection', 'Simulation scénarios', 'Gestion équipes'],
          tags: ['unity', 'c#', '3d-temps-réel', 'training', 'education'],
          type: 'projet',
        },
        {
          id: 27,
          featured: false,
          name: 'suez/maintenance-generateurs-de-vapeurs',
          badge: 'C# / 3D Developer',
          period: '2014 – 2015',
          context: 'Maintenance Générateurs de Vapeurs — Serious Game pour arrêts de tranche',
          desc: 'Serious game destiné à préparer les interventions durant les arrêts de tranche pour la maintenance des générateurs de vapeurs. Simulation 3D temps réel, développement C# pour reproduire les procédures complexes de maintenance en environnement nucléaire.',
          tasks: ['Maintenance nucléaire', 'Simulation 3D', 'Développement C#'],
          tags: ['unity', 'c#', '3d-temps-réel', 'nuclear', 'training', 'desktop'],
          type: 'projet',
        },
        {
          id: 28,
          featured: false,
          name: 'chu-caen/emsim-basic',
          badge: 'C# / 3D Developer',
          period: '2013 – 2015',
          context: 'Radioprotection pour la Chirurgie Interventionnelle',
          desc: 'Simulation 3D pour la formation des équipes chirurgicales. Dosimétrie en temps réel, visualisation des zones sensibles aux radiations, protocole de radioprotection opérateur.',
          tasks: ['Simulation médicale', 'Dosimétrie temps réel', 'Radioprotection opérateur'],
          tags: ['unity', 'c#', '3d-temps-réel', 'medical', 'healthcare'],
          type: 'projet',
        },
    ],
  },
]

export const mockSkills: Skill[] = [
  {
    cat: 'Frameworks',
    featured: false,
    tags: [
      { l: 'Vue3', k: 'vue' },
      { l: 'React', k: 'react' },
      { l: 'single-spa', k: 'spa' },
      { l: 'Jest', k: 'jest' },
      { l: 'Flutter', k: 'flutter' },
      { l: 'Unity 3D', k: 'unity' },
    ],
  },
  {
    cat: 'Outils',
    featured: false,
    tags: [
      { l: 'Docker', k: 'docker' },
      { l: 'Git', k: 'git' },
      { l: 'Postman', k: 'green' },
      { l: 'Jira', k: 'jira' },
      { l: 'Figma', k: 'figma' },
    ],
  },
]

export const mockFormation: Formation[] = [
  {
    label: '📌 Formations',
    title: 'React · TypeScript',
    sub: 'Datacorp · 2026',
    meta: 'Formation approfondie sur React et les bonnes pratiques front-end modernes',

  },
  {
    label: '📌 Formations',
    title: 'TypeScript · Docker · Vue.js',
    sub: 'Datacorp · 2023',
    meta: 'Formations professionnelles sur les technologies web modernes utilisées dans mes missions actuelles',

  },
  {
    label: '📌 Formations',
    title: 'Stage Polymorph',
    sub: 'Stage fin de license · 2013',
    meta: 'Design graphique · Communication visuelle',

  },
  {
    label: '📌 Diplome',
    title: 'Licence 3D Temps Réel',
    sub: '3DI Laval · 2012–2013',
    meta: '3D temps réel · Réalité virtuelle · Unity 3D',

  },
  {
    label: '📌 Diplome',
    title: 'BTS Communication Visuelle opt. Multimédia',
    sub: '3DI Laval · 2010–2012',
    meta: 'Multimédia · Web · Vidéo',

  },
]

export const mockActivity: Activity[] = []

export const mockProjects: Project[] = [
  {
    id: 1,
    name: 'schneider-electric/iiot-edge-ieca',
    company: 'Schneider Electric',
    role: 'Frontend Developer',
    period: '2023 – 2026',
    context: 'Industrial Automation IIoT 2.0 Edge (IECA)',
    desc: 'Plateforme Cloud IIoT pour l\'automatisation industrielle. Tablespaces de contrôle d\'usines, monitoring en temps réel des machines, architecture micro-frontend.',
    stack: 'Vue 3.4 · TypeScript 5.x · single-spa 6 · Docker · Jest · HTML5 · CSS3 · Figma · Jira',
    tags: ['vue3', 'ts', 'single-spa', 'docker', 'jest', 'html', 'css', 'git', 'figma'],
  },
  {
    id: 2,
    name: 'schneider/aoa-ar-app',
    company: 'Schneider Electric',
    role: 'C# / Unity Developer',
    period: '2017 – 2023',
    context: 'Augmented Operator Advisor (AOA) — Industrial AR Application',
    desc: 'Application AR multiplateforme pour opérateurs industriels Schneider Electric. Interfaces opérateur en AR, overlay des données machines en temps réel, gestion complexe de la couche AR.',
    stack: 'Unity 3D · C# · ARKit · ARCore · Figma · iOS · Android · Windows',
    tags: ['unity', 'c#', 'ar', 'mobile', 'uiux', 'figma', 'agile'],
  },
  {
    id: 3,
    name: 'simulhom',
    company: 'Oreka Ingénierie',
    role: 'C# / Unity Developer',
    period: '2015 – 2017',
    context: 'Outil de prévention des TMS (Troubles Musculo-Squelettiques)',
    desc: 'Simulateur ergonomique 3D pour la prévention des TMS en milieu industriel. Analyse posturale temps réel, feedback visuel des risques, interface opérateur intuitive.',
    stack: 'Unity 3D · C# · 3ds Max · Ergonomie · Biomécanique',
    tags: ['unity', 'c#', '3d-temps-réel', 'vr', 'ergonomics'],
  },
  {
    id: 4,
    name: 'oreka/dosicase',
    company: 'Oreka Ingénierie',
    role: 'Conception & Design UI/UX',
    period: '2015 – 2017',
    context: 'Dosicase — Simulateur de radioactivité pour chantiers école',
    desc: 'Outil de simulation de radioactivité destiné aux chantiers école pour la formation en radioprotection. Conception de l\'interface utilisateur et design UX pour rendre accessible la compréhension des risques radiologiques. Focus sur la pédagogie et l\'apprentissage pratique.',
    stack: 'UX/UI Design · Simulation · Radioprotection · Web Interface',
    tags: ['uiux', 'design', 'web', 'radioprotection', 'dosimetry', 'figma'],
  },
  {
    id: 5,
    name: 'areva/emem',
    company: 'AREVA / Oreka Ingénierie',
    role: 'C# / 3D Developer',
    period: '2014 – 2016',
    context: 'EMEM (Enceinte Mobile d\'Évacuation de Matériel) — Nuclear Safety',
    desc: 'Simulation 3D interactive d\'une enceinte mobile nucléaire. Visualisation 3D des flux, gestion des matériaux radioactifs, interfaces de contrôle temps réel pour opérateurs.',
    stack: 'Unity 3D · C# · SolidWorks · Nuclear simulation · WPF',
    tags: ['unity', 'c#', '3d-temps-réel', 'nuclear', 'desktop'],
  },
  {
    id: 6,
    name: 'edf/aeroball',
    company: 'EDF / Oreka Ingénierie',
    role: 'C# / 3D Developer',
    period: '2014 – 2015',
    context: 'Aeroball — Serious Game pour poste de contrôle nucléaire',
    desc: 'Serious game de formation pour l\'utilisation du poste de contrôle Aeroball en milieu nucléaire. Simulation 3D interactive, développement C# et modélisation 3D pour reproduire fidèlement les procédures opérationnelles.',
    stack: 'Unity 3D · C# · Modélisation 3D · Nuclear Training · Simulation',
    tags: ['unity', 'c#', '3d-temps-réel', 'nuclear', 'training', 'desktop'],
  },
  {
    id: 7,
    name: 'suez/serious-game-radioprotection',
    company: 'SUEZ / Oreka Ingénierie',
    role: 'C# / 3D Developer',
    period: '2014 – 2015',
    context: 'Formation en Radioprotection — Nuclear Safety Training',
    desc: 'Module de formation interactive 3D sur la radioprotection et les procédures de sécurité nucléaire. Simulations de scénarios d\'accident, gestion des équipes de secours.',
    stack: 'Unity 3D · C# · 3D Modeling · Educational Design',
    tags: ['unity', 'c#', '3d-temps-réel', 'training', 'education'],
  },
  {
    id: 8,
    name: 'suez/maintenance-generateurs-de-vapeurs',
    company: 'SUEZ / Oreka Ingénierie',
    role: 'C# / 3D Developer',
    period: '2014 – 2015',
    context: 'Maintenance Générateurs de Vapeurs — Serious Game pour arrêts de tranche',
    desc: 'Serious game destiné à préparer les interventions durant les arrêts de tranche pour la maintenance des générateurs de vapeurs. Simulation 3D temps réel, développement C# pour reproduire les procédures complexes de maintenance en environnement nucléaire.',
    stack: 'Unity 3D · C# · 3D Temps Réel · Nuclear Maintenance · Simulation',
    tags: ['unity', 'c#', '3d-temps-réel', 'nuclear', 'training', 'desktop'],
  },
  {
    id: 9,
    name: 'chu-caen/emsim-basic',
    company: 'CHU de Caen / Oreka Ingénierie',
    role: 'C# / 3D Developer',
    period: '2013 – 2015',
    context: 'Radioprotection pour la Chirurgie Interventionnelle',
    desc: 'Simulation 3D pour la formation des équipes chirurgicales. Dosimétrie en temps réel, visualisation des zones sensibles aux radiations, protocole de radioprotection opérateur.',
    stack: 'Unity 3D · C# · Medical 3D · Dosimetry · Healthcare',
    tags: ['unity', 'c#', '3d-temps-réel', 'medical', 'healthcare'],
  },
  {
    id: 10,
    name: 'alexandre-plana/cv-react',
    company: 'Projet personnel',
    role: 'Développeur Front End',
    period: '2026',
    context: 'CV interactif React',
    desc: 'Application CV interactive construite avec React et TypeScript. Travail sur l\'UX, la structure des données et l\'export de contenu.',
    stack: 'React · TypeScript · Vite · UI/UX Design',
    tags: ['react', 'ts', 'vite', 'uiux', 'design'],
  },
]

export const mockPersonalProjects: PersonalProject[] = [
  {
    id: 1,
    name: 'ohlabo',
    kind: 'Plateforme éducative',
    role: 'Développeur full stack',
    desc: "Plateforme éducative 6-11 ans : le cycle de l'eau, les volcans ou les incendies expliqués en dioramas voxel manipulables bloc par bloc. Moteur de simulation déterministe sans aucune dépendance, triple rendu d'un même modèle — 3D, coupe 2D, DOM accessible — et mode hors-ligne pensé pour l'école.",
    details: "Le voxel n'est pas un choix esthétique : il sert à montrer l'intérieur des phénomènes — on coupe un volcan comme un gâteau pour voir la chambre magmatique. L'architecture est verrouillée par 26 décisions documentées, et le backlog outillé compte 95 tâches en 17 lots, vérifiées en CI.",
    highlights: [
      'Moteur voxel déterministe zéro dépendance — Math.random et imports interdits, vérifié mécaniquement par lint en CI',
      "Triple rendu d'un même modèle : 3D (three.js/TSL, WebGL + WebGPU), coupe 2D de repli et arbre DOM d'accessibilité",
      'Contenu pédagogique piloté par manifestes versionnés avec validateur CLI',
      "Suivi d'apprentissage xAPI minimisé par conception : aucun classement entre enfants, ni geste ni caméra",
      'Monorepo pnpm en 6 paquets : engine, render-3d, render-2d, a11y, player, shell',
    ],
    stack: ['ts', 'three.js', 'webgpu', 'vite', 'vitest'],
    period: '2026',
    status: 'actif',
  },
  {
    id: 2,
    name: 'kin',
    kind: 'App auto-hébergée',
    role: 'Développeur full stack',
    desc: "Mémoire numérique familiale auto-hébergée : photos, vidéos et documents stockés de façon fiable chez soi, consultables via une galerie Android et une administration 100 % locale. Phase de cadrage aboutie : vision, décisions d'architecture et roadmap complète en 13 livrables.",
    details: "Un serveur familial pensé comme une mémoire numérique : les souvenirs arrivent, sont stockés de façon fiable et restent consultables par la famille — sans cloud tiers. Le cadrage est complet : 17 documents de décision, 13 fiches de features et une roadmap en livrables (L0 → L12) pilotée par iasit.",
    highlights: [
      'Upload et stockage fiables : machine à états de synchronisation, checksums, backup/restore local',
      'Galerie Android + administration web strictement locale (local-only documenté)',
      "Appairage d'appareils, groupes, audiences et visibilité des souvenirs",
      'Accès réseau prévu via Cloudflare Tunnel, monorepo Node/TypeScript avec packages partagés',
    ],
    stack: ['node', 'ts', 'android', 'rest', 'self-hosted'],
    period: '2026',
    status: 'en conception',
  },
  {
    id: 3,
    name: 'specia',
    kind: 'Simulation scientifique',
    role: 'Développeur full stack',
    desc: "Observatoire d'évolution émergente : une population d'organismes naît, mute, se recombine et forme des espèces sur une grille hexagonale — rien n'est scripté, tout émerge. Moteur headless déterministe (RNG seedée, hash d'état), simulation en Web Workers et suivi en direct de 12 traits génétiques.",
    details: "L'objectif n'est pas de programmer l'évolution mais de créer les conditions où elle émerge : certains patrimoines génétiques deviennent plus fréquents, des espèces se forment, et l'observatoire rend ces données belles et manipulables. Le projet a été volontairement remis à zéro en cours de route pour recentrer le cœur — l'ancienne version reste archivée.",
    highlights: [
      'Génétique complète : génome, phénotype, mutation, recombinaison, spéciation classée automatiquement',
      'Moteur headless déterministe : RNG seedée, hash d\'état, exécutable sans UI pour la mesure',
      'Génération de monde déterministe (biomes, hydrologie, terrain) avec bibliothèque locale de terrains rechargeables',
      'Atlas PixiJS 160×90 avec overlays, caméra pan/zoom et 12 traits moyens suivis en direct',
      "Outillage d'analyse hors-ligne : bench, sondes de spéciation, tests d'endurance, export de données",
    ],
    stack: ['react', 'ts', 'pixijs', 'web workers', 'vitest'],
    period: '2026',
    status: 'en pause',
  },
  {
    id: 4,
    name: 'iasit',
    kind: 'Outillage dev',
    role: 'Développeur full stack',
    desc: 'Outil de pilotage pour le développement assisté par agents IA : tâches, exécutions et findings traçables, génération de prompts canoniques (run / verify / fix) et orchestration de lots complets. Il pilote le backlog de mes autres projets persos — 580 commits en deux mois.',
    details: "Né du développement assisté par agents IA : l'outil trace tout ce qui compte (tâches, exécutions, findings) et génère des prompts canoniques exécutés par un agent externe — l'app elle-même n'exécute aucune IA, le périmètre est volontairement borné. C'est le méta-outil du lot : kin et vorrery embarquent ses données de pilotage.",
    highlights: [
      'Formats canoniques Task / TaskExecution / VerificationFinding, statut comme source de vérité unique',
      'Prompts run / verify / fix / next en double rendu : fullPrompt + compactInstruction',
      "Batch : orchestration d'une plage de tâches (run → verify → fix → re-verify) avec parité CLI/runtime",
      "Registry d'agents et chaîne de handoff documentée (analyst → … → release-operator)",
      'Graphe de contexte Sigma.js avec mode focus, index de fichiers du dépôt, réconciliation d\'artefacts',
    ],
    stack: ['react', 'ts', 'zod', 'tailwind', 'node'],
    period: '2026',
    status: 'en service',
  },
  {
    id: 5,
    name: 'lavis · Aquarelle Studio',
    kind: 'Simulateur temps réel',
    role: 'Développeur full stack',
    desc: "Simulateur d'aquarelle physique dans le navigateur : l'eau s'écoule, le pigment granule et fonce en séchant, comme sur du vrai papier. Solveur fluide shallow-water (modèle SIGGRAPH '97) implémenté from scratch en shaders WebGL2, rendu optique Kubelka-Munk et 52 pigments calibrés à la main.",
    details: "Ré-implémentation from scratch du modèle shallow-water de Curtis et al. (Computer-Generated Watercolor, SIGGRAPH 1997) : l'eau s'écoule selon la pente et le grain du papier, le pigment est advecté, granule dans les creux et fonce aux bords en séchant. Le rendu compose les couches optiquement via Kubelka-Munk — pas de blending RGB naïf.",
    highlights: [
      'Solveur fluide 100 % shaders WebGL2 : splat, advection semi-lagrangienne, Jacobi ×20, capillarité, edge darkening',
      '52 pigments calibrés à la main (masstone/undertone, granulation, staining), 12 simultanés via slots dynamiques',
      'Papier procédural à seed déterministe : carte de hauteur + carte d\'absorption, 3 presets',
      "Pinceau à pression avec pointer/coalesced events, mode X-ray sur l'état interne du solveur",
      'Vérification headless Playwright + SwiftShader avec scénarios rejouables',
    ],
    stack: ['ts', 'webgl2', 'glsl', 'react', 'playwright'],
    period: '2026',
    status: 'actif',
  },
  {
    id: 6,
    name: 'vorrery',
    kind: 'App web 3D',
    role: 'Développeur full stack',
    desc: "Forge orbitale 3D : des planètes procédurales déterministes se construisent couche par couche sous les yeux de l'utilisateur, puis rejoignent une maquette de système vivante. Laboratoire de gravité à 32 corps, trous noirs à lentille gravitationnelle, génération en Web Workers et couche mathématique intégralement testée.",
    details: "Le parti-pris : rendre la génération visible. Chaque planète traverse une timeline de couches (orbite, proto-sphère, géologie, relief, hydrosphère, climat, biomes, atmosphère, lunes…) où chaque étape modifie la scène à l'écran. Des contraintes physiques simplifiées (masse, gravité, albédo, pression) orientent l'archétype et les avertissements d'habitabilité.",
    highlights: [
      'Forge procédurale déterministe à couches visibles, génération en Web Workers hors thread principal',
      'Laboratoire de gravité : 32 corps, gizmos masse/position/vélocité, prédictions de trajectoire, sphères de Hill, undo/redo',
      "Objets compacts : trous noirs (disque d'accrétion Doppler, lentille gravitationnelle), pulsars, étoiles à neutrons",
      'Scène kids avec sonification orbitale et narration audio',
      'Couche mathématique intégralement testée : chaque module *.ts a son *.test.ts',
    ],
    stack: ['react', 'three.js', 'r3f', 'ts', 'glsl', 'web workers'],
    period: '2026',
    status: 'actif',
  },
]
