import { Profile, Experience, Skill, Formation, Activity } from '../types'

export const mockProfile: Profile = {
  name: 'Alexandre Plana',
  handle: 'alexandre-plana',
  title: 'Développeur Front End Web',
  subtitle: 'Industrie · UI/UX · Multi Plateforme',
  bio: 'Développeur Front End spécialisé industrie depuis 13 ans. D\'abord sur des interfaces 3D / VR pour EDF, RTE, AREVA et DCNS, puis sur une application AR mobile multi-plateforme, aujourd\'hui sur des architectures web micro-frontend pour l\'IIoT. La techno évolue, le domaine reste : des interfaces complexes pour des environnements industriels exigeants. Sensibilité UI/UX forgée par la pratique du design sur l\'ensemble du parcours.',
  company: 'Consultant R&D · Datacorp / Schneider Electric',
  location: 'France',
  email: 'alexandre.plana@gmail.com',
  phone: '06.71.03.97.84',
  followers: 142,
  following: 38,
  contributions: 1842,
  seeking: 'Poste Front End web dans un contexte industriel · Vue.js ou React · TypeScript · micro-frontend · équipe orientée qualité & UX',
  langs: [
    { label: 'Français', level: 'Natif' },
    { label: 'Anglais', level: 'Technique' },
  ],
  languages: [
    { name: 'TypeScript', pct: 26, color: '#3178c6' },
    { name: 'Vue.js', pct: 22, color: '#41b883' },
    { name: 'JavaScript', pct: 16, color: '#f1e05a' },
    { name: 'C#', pct: 18, color: '#178600' },
    { name: 'Dart', pct: 10, color: '#00b4d8' },
    { name: 'Unity/HLSL', pct: 8, color: '#a97bff' },
  ],
  awards: [
    { year: '2012', title: 'Laval Virtual', desc: 'Prix du jury — reconstitution virtuelle Abbaye d\'Evron' },
    { year: '2011', title: 'Laval Virtual', desc: '1ère place — Hackaton réalité augmentée' },
  ],
  interests: ['🎮 Jeux', '🚵 VTT', '🥾 Rando', '🍳 Cuisine'],
  uiuxHighlight: {
    label: '🎨 Culture UI/UX',
    desc: 'Pratique du design sur l\'ensemble du parcours — de la maquette Figma au composant en production.',
    tools: ['Figma', 'Adobe XD', 'Design System', 'Prototypage'],
  },
}

export const mockExperiences: Experience[] = [
  {
    id: 1,
    company: 'Schneider Electric',
    employer: 'Consultant R&D — Datacorp',
    period: '2017 – 2026',
    type: 'consulting',
    missions: [
      {
        id: 11,
        featured: true,
        name: 'schneider/iiot-edge-ieca',
        badge: 'Lead FE Développeur',
        period: '2023 – 2026',
        context: 'Industrial Automation IIoT 2.0 Edge (IECA)',
        desc: 'Développement d\'Edge compute apps industrielles sur la plateforme Goodenough (single-spa). Architecture micro-frontend IIoT 2.0, intégration de composants Vue 3 + TypeScript en équipe. Conception UI des tableaux de bord industriels en lien avec les équipes UX.',
        metrics: [
          { value: '6', label: 'sites industriels\ndéployés' },
          { value: '40%', label: 'réduction temps\nde chargement' },
          { value: 'Vue 3', label: 'stack\nprincipale' },
        ],
        stack: 'Vue 3.4 · TypeScript 5.x · single-spa 6 · Jest · HTML5 · CSS3 · Git · JSS · Figma · Jira',
        tags: ['vue', 'ts', 'spa', 'jest', 'html', 'css', 'git', 'figma'],
        lang: 'Vue.js',
        langColor: '#41b883',
        stars: '1.2k',
      },
      {
        id: 12,
        featured: false,
        name: 'schneider/aoa-ar-app',
        badge: 'Développeur C# / Unity',
        period: '2017 – 2023',
        context: 'Augmented Operator Advisor (AOA) — Application AR industrielle',
        desc: 'Développement pendant 6 ans d\'une application AR multi-plateforme (Android, iOS, Windows) pour opérateurs industriels Schneider Electric. Conception et implémentation des interfaces opérateur, gestion des états complexes de la couche AR.',
        metrics: [
          { value: '6 ans', label: 'développement\ncontinu' },
          { value: '3', label: 'plateformes\nsimultanées' },
          { value: 'AR', label: 'temps réel\nterrain' },
        ],
        stack: 'Unity 3D · C# · ARKit · ARCore · Figma · UI/UX · Scrum · Jira',
        tags: ['unity', 'csharp', 'ar', 'mobile', 'uiux', 'figma', 'agile'],
        lang: 'C#',
        langColor: '#178600',
        stars: '980',
      },
    ],
  },
  {
    id: 2,
    company: 'Oreka Ingénierie',
    employer: 'Développeur C# / Unity 3D',
    period: '2013 – 2017',
    type: 'employee',
    missions: [
      {
        id: 21,
        featured: false,
        name: 'oreka/xr-projects',
        badge: 'Développeur C# / Unity 3D',
        period: '2013 – 2017',
        context: 'Projets VR/AR industriels — EDF · RTE · AREVA · DCNS · Énergies renouvelables',
        desc: 'Développement d\'interfaces 3D et de simulations VR/AR pour grands comptes de l\'industrie lourde et de l\'énergie. Projets livrés : EDF Aeroball, AREVA EMEM, DCNS simulateurs, RTE supervision, SUEZ radio protection.',
        metrics: [
          { value: '6+', label: 'projets\nindustriels' },
          { value: '5', label: 'clients grands\ncomptes' },
          { value: 'VR/AR', label: 'temps réel\nUnity 3D' },
        ],
        stack: 'Unity 3D · C# · WPF · WinForm · SolidWorks · 3ds Max · Figma',
        tags: ['unity', 'csharp', 'vr', 'uiux', 'figma', 'desktop'],
        lang: 'C#',
        langColor: '#178600',
        stars: '543',
      },
    ],
  },
]

export const mockSkills: Skill[] = [
  {
    cat: '⭐ Développement Web',
    featured: true,
    tags: [
      { l: 'Vue.js', k: 'vue' },
      { l: 'TypeScript', k: 'ts' },
      { l: 'JavaScript', k: 'js' },
      { l: 'HTML5', k: 'html' },
      { l: 'CSS3', k: 'css' },
      { l: 'Jest', k: 'jest' },
      { l: 'single-spa', k: 'spa' },
      { l: 'Git', k: 'git' },
    ],
  },
  {
    cat: '// UI/UX Design',
    featured: false,
    tags: [
      { l: 'Figma', k: 'figma' },
      { l: 'Adobe XD', k: 'figma' },
      { l: 'User Research', k: 'uiux' },
      { l: 'Wireframing', k: 'uiux' },
      { l: 'Prototypage', k: 'uiux' },
      { l: 'Design System', k: 'uiux' },
      { l: 'UX industriel', k: 'uiux' },
      { l: 'UI opérateur', k: 'uiux' },
    ],
  },
  {
    cat: '// Développement Mobile',
    featured: false,
    tags: [
      { l: 'Flutter', k: 'flutter' },
      { l: 'Dart', k: 'dart' },
      { l: 'iOS', k: 'mobile' },
      { l: 'Android', k: 'mobile' },
    ],
  },
  {
    cat: '// 3D Temps Réel & XR',
    featured: false,
    tags: [
      { l: 'Unity 3D', k: 'unity' },
      { l: 'C#', k: 'csharp' },
      { l: 'Réalité Augmentée', k: 'ar' },
      { l: 'Réalité Virtuelle', k: 'vr' },
      { l: '3ds Max', k: '3d' },
    ],
  },
  {
    cat: '// Outils & Méthodologie',
    featured: false,
    tags: [
      { l: 'Git', k: 'git' },
      { l: 'Jira', k: 'jira' },
      { l: 'Scrum', k: 'agile' },
      { l: 'Agile', k: 'agile' },
    ],
  },
  {
    cat: '// Soft Skills',
    featured: false,
    tags: [
      { l: 'Créativité', k: 'green' },
      { l: 'Travail d\'équipe', k: 'green' },
      { l: 'Adaptabilité', k: 'green' },
      { l: 'Curiosité', k: 'green' },
    ],
  },
]

export const mockFormation: Formation[] = [
  {
    label: '📌 Licence',
    title: 'Licence 3D Temps Réel',
    sub: '3DI Laval · 2012–2013',
    meta: '3D temps réel · Réalité virtuelle · Unity 3D',
    bg: '#dcfce7',
    color: '#166534',
  },
  {
    label: '📌 BTS',
    title: 'BTS Communication Visuelle opt. Multimédia',
    sub: '3DI Laval · 2010–2012',
    meta: 'Print · Multimédia · Web · Vidéo',
    bg: '#dcfce7',
    color: '#166534',
  },
  {
    label: '📌 Formations',
    title: 'C# · Dart · TypeScript · Flutter · UI-UX',
    sub: 'Datacorp · 2017',
    meta: 'Formations professionnelles certifiées',
    bg: '#dbeafe',
    color: '#1e40af',
  },
  {
    label: '📌 Stage',
    title: 'Stage Polymorph (3S)',
    sub: 'YOM Graphic Design · Prisma (53)',
    meta: 'Design graphique · Communication visuelle',
    bg: '#dcfce7',
    color: '#166534',
  },
]

export const mockActivity: Activity[] = [
  {
    id: 1,
    icon: '🔀',
    type: 'blue',
    action: 'Merged a PR in',
    repo: 'schneider/iiot-edge-ieca',
    detail: 'feat: new Edge dashboard widget',
    time: '3 days ago',
  },
  {
    id: 2,
    icon: '⭐',
    type: 'green',
    action: 'Starred',
    repo: 'vuejs/core and vitejs/vite',
    detail: '',
    time: '1 week ago',
  },
  {
    id: 3,
    icon: '💬',
    type: 'orange',
    action: 'Commented on issue #88 in',
    repo: 'schneider/iiot-edge-ieca',
    detail: 'single-spa routing fix',
    time: '2 weeks ago',
  },
  {
    id: 4,
    icon: '🎉',
    type: 'green',
    action: 'Released v3.1.0 in',
    repo: 'schneider/aoa-ar-app',
    detail: 'Multi-platform AR build',
    time: '1 month ago',
  },
]
